changelogs/unreleased/-1vrhjph.yml, src/App.vue
=> Removed filter from picklist page (#1vrhjph)

README.md
=> Added: readme file(readme)

public/index.html
=> updated title of picking app (#1w9gm4n)

src/views/Settings.vue
=> Updated the markup #1y2ract

src/api/index.ts, src/views/Login.vue, src/views/Settings.vue
=> Improved: code to hide option to set baseURL if value available in '.env' file (#29wgkkh)

README.md
=> Added GitHub contribution badge

src/locales/en.json, src/store/modules/picklist/actions.ts, src/views/Picklists.vue
Closes #71 
Added message and toast when no picklists are there.
=> Implemented message display in UI when no picklists found (#31fnaw8)

package-lock.json, package.json, release-notes.md
=> Updated: application version and release notes for minor release

src/components/Picklist-item.vue
=> Fixed: code to show cursor while hovering on picklist (#85zrnrmdh)

package-lock.json, package.json
=> Updated: version for minor release (1.4.0)

package-lock.json, package.json
=> Updated: app version for minor release (1.5.0)

package-lock.json, package.json, release-notes.md
=> Updated: release notes for minor release(1.5.0)

package-lock.json, package.json
=> Updated: app version for minor release

package-lock.json, package.json
=> Updated: app version for patch release

src/components/Picklist-item.vue, src/services/PicklistService.ts, src/store/modules/picklist/actions.ts, src/store/modules/picklist/mutations.ts, src/views/Picklist-Detail.vue, src/views/Settings.vue
Closes #120 
Replaced the picklist API with performFind, this fixed the issue where details for picklist by users other than the currently logged-in user were not being fetched.
[Screencast from 24-04-23 03:21:57 PM IST.webm](https://user-images.githubusercontent.com/59442907/233962939-176ca0b1-0aec-4a10-9ca3-8c40a56af790.webm)
=> Implemented: usage of performFind for fetching picklist details (#85zry5kg0)

.gitignore, src/components/Picklist-filters.vue, src/store/modules/user/actions.ts
Additionally updated the gitignore with VSCode history plugin files and firebase files
#125 
Closes #
=> Fixed: picklist filters not being reset on logout (#125)

src/views/Picklists.vue
=> Implemented: Pull to refresh on picklists screen (#123)

src/locales/en.json, src/views/Picklist-Detail.vue
External barcode readers require an input field to input submit their scanned value.
Closes #126 
=> Implemented: Support for external scanner (#126)

src/components/Picklist-item.vue
=> Improved: Show picklist ID for the picklist with name (#124)

package-lock.json, package.json
=> Updated: app version for minor release (1.8.0)

package-lock.json, package.json, release-notes.md
=> Updated: app version and release notes for minor release(v1.9.0)

package-lock.json, package.json
=> Updated: app version for minor release (1.9.0)

src/views/Picklist-Detail.vue
=> Fixed: cleared product ID on search (#139)

package-lock.json, package.json
=> Updated: app version for minor release (1.10.0)

package-lock.json, package.json, release-notes.md
=> Updated: app version for minor release (1.11.0)

package-lock.json, package.json
=> Updated: package and lock file for minor release(v1.12.0)

package-lock.json, package.json
=> Updated: package lock and package file for minor release(v1.14.0)

package-lock.json, package.json
=> Improved: app version in package and lock file for minor release(v1.15.0)

src/store/modules/picklist/index.ts, src/store/modules/user/actions.ts
=> Implemented: enabled both picklist filters by default (#181)

package-lock.json, package.json
Closes #
Updated: app version for the minor release (1.16.0).
=> Updated: app version for the minor release (1.16.0).

package-lock.json, package.json
=> Updated: app version for minor release (v1.17.0)

src/locales/en.json, src/views/Picklist-Detail.vue
=> Update en.json for `complete picklist` message

package-lock.json, package.json
=> Updated: app version for patch release (v1.17.1)

src/store/modules/party/actions.ts
Closes #201
Added handling for name coming in groupName for the facility login user.
=> Fixed: facility login user name not showing up (#201)

src/adapter/index.ts, src/services/UserService.ts, src/store/modules/party/actions.ts, src/store/modules/picklist/actions.ts, src/store/modules/product/actions.ts, src/store/modules/user/actions.ts, src/utils/index.ts, src/views/TimezoneModal.vue
Related Issue #200
Improved code to use hasError method form the oms-api since app specific method lacks handling for error in api response resulting in app break on api failure.
=> Improved: used hasError from the oms-api instead of using app specific method and updated the payload for fetchProducts (#200)

src/main.ts
https://github.com/hotwax/picking/issues/187
- Added a entry in `main` file to fix html tags not working in the translations.
=> Fixed: html tags not working in the translations (#187)

package-lock.json, package.json
=> Improved: app version in the package and lock file for minor release(v1.19.0)
